export const Colors = {
  background: 'var(--color-background)',
  surface: 'var(--color-surface)',
  surfaceDim: 'var(--color-surfaceDim)',
  surfaceContainerLowest: 'var(--color-surfaceContainerLowest)',
  surfaceContainerLow: 'var(--color-surfaceContainerLow)',
  surfaceContainer: 'var(--color-surfaceContainer)',
  surfaceContainerHigh: 'var(--color-surfaceContainerHigh)',
  surfaceContainerHighest: 'var(--color-surfaceContainerHighest)',
  surfaceBright: 'var(--color-surfaceBright)',
  surfaceVariant: 'var(--color-surfaceVariant)',
  onSurface: 'var(--color-onSurface)',
  onSurfaceVariant: 'var(--color-onSurfaceVariant)',
  primary: 'var(--color-primary)',
  primaryContainer: 'var(--color-primaryContainer)',
  inversePrimary: 'var(--color-inversePrimary)',
  accent: 'var(--color-accent)',
  onPrimary: 'var(--color-onPrimary)',
  secondary: 'var(--color-secondary)',
  secondaryContainer: 'var(--color-secondaryContainer)',
  onSecondary: 'var(--color-onSecondary)',
  tertiary: 'var(--color-tertiary)',
  tertiaryContainer: 'var(--color-tertiaryContainer)',
  error: 'var(--color-error)',
  errorContainer: 'var(--color-errorContainer)',
  outline: 'var(--color-outline)',
  outlineVariant: 'var(--color-outlineVariant)',
} as const
